test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/testsets/Set14_HR
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale_min: 4
      scale_max: 4
  batch_size: 1
eval_type: benchmark-4
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}