test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/DIV2K/DIV2K_valid_HR
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale_min: 3
      scale_max: 3
  batch_size: 1
eval_type: div2k-3
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}