train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/DIV2K800/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../datasets/DIV2K100/DIV2K100_crop_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lmlte
  args:
    encoder_spec:
      name: rdn
      args:
        no_upsampling: true
    imnet_spec:
      name: lmmlp
      args:
        out_dim: 3
        hidden_dim: 16
        hidden_depth: 8
        mod_scale: True
        mod_shift: True
    hypernet_spec:
      name: mlp
      args:
        out_dim: 288
        hidden_list: [ 288 ]
    hidden_dim: 128
    local_ensemble: true
    cell_decode: true
    mod_input: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 50

resume: ./save/epoch-last.pth